// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBooBYQv5XaszDGX3XW62XWaOJTP3danxI',
    appId: '1:692109531022:web:817d886f861a755cbd36df',
    messagingSenderId: '692109531022',
    projectId: 'filedoc-64d48',
    authDomain: 'filedoc-64d48.firebaseapp.com',
    storageBucket: 'filedoc-64d48.firebasestorage.app',
    measurementId: 'G-LSK8DYNZS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNT4XvFb7AuPWtz1pH1NgAuhs2zQIcVxw',
    appId: '1:692109531022:android:c3ecff1f490a8322bd36df',
    messagingSenderId: '692109531022',
    projectId: 'filedoc-64d48',
    storageBucket: 'filedoc-64d48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOoiTIaQMr1h0bODBLnwhofPh2eTi_Ck',
    appId: '1:692109531022:ios:f122707f58b4868ebd36df',
    messagingSenderId: '692109531022',
    projectId: 'filedoc-64d48',
    storageBucket: 'filedoc-64d48.firebasestorage.app',
    androidClientId: '692109531022-282o3n78t33l9g4s100erppadttqoto1.apps.googleusercontent.com',
    iosClientId: '692109531022-de7iic1c1mtf27j23lt7kq7g5vj35c4a.apps.googleusercontent.com',
    iosBundleId: 'com.ignito.filedockminiadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOoiTIaQMr1h0bODBLnwhofPh2eTi_Ck',
    appId: '1:692109531022:ios:875509686ea8aab3bd36df',
    messagingSenderId: '692109531022',
    projectId: 'filedoc-64d48',
    storageBucket: 'filedoc-64d48.firebasestorage.app',
    iosBundleId: 'com.example.fileDock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBooBYQv5XaszDGX3XW62XWaOJTP3danxI',
    appId: '1:692109531022:web:1b25f93ea2e59384bd36df',
    messagingSenderId: '692109531022',
    projectId: 'filedoc-64d48',
    authDomain: 'filedoc-64d48.firebaseapp.com',
    storageBucket: 'filedoc-64d48.firebasestorage.app',
    measurementId: 'G-Q9JNSLYCVL',
  );
}